# Generated by Django 4.0.6 on 2023-01-28 23:09

from django.db import migrations, models
import django.db.models.deletion
import workouts.models.workout


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(help_text='Dati numele scopului antrenamentului', max_length=20)),
            ],
            options={
                'ordering': ['goal_name'],
            },
        ),
        migrations.AlterField(
            model_name='disability',
            name='name',
            field=models.CharField(help_text='Dati numele dizabilitatii', max_length=20),
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Denumiti antrenamentul', max_length=20)),
                ('equipment', models.CharField(choices=[('Nu, antrenament acasa', 'Nu, antrenament acasa'), ('Da, antrenament la sala', 'Da, antrenament la sala')], default='Nu, antrenament acasa', max_length=25)),
                ('level', models.CharField(choices=[('Incepator', 'Incepator'), ('Mediu', 'Mediu'), ('Avansat', 'Avansat')], default='Incepator', max_length=20)),
                ('length', models.IntegerField(help_text='Numarul de zile', validators=[workouts.models.workout.validate_length])),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=workouts.models.workout.image_path)),
                ('disability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.disability')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.goal')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
