# Generated by Django 4.0.6 on 2023-02-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_disability_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='video',
        ),
    ]
